### ISSUE TITLE
odoo 8 web_list_view_sequence

### ISSUE THREAD

**Issue by filsys** [Elico-Corp/odoo-8.0#100]
Try to open a list (Window Action) and find this error:
Uncaught Error: QWeb2 - template['ListView.row']: Runtime Error: TypeError: dict.fct_colorize is not a function

**Comment by elicoidal** [comment]
Hi @filsys thanks for the feedback.
We will try to reproduce the error and will come back to you ( @siyuancn )

**Comment by elicoidal** [comment]
Closing for old and not reproducible issue
