### ISSUE TITLE
Missing column in table header

### ISSUE THREAD

**Issue by mharenz** [Elico-Corp/odoo-8.0#101]
module: web_list_view_sequence
version: {8.0}

**Steps to reproduce**
Use any Form-View and Switch to Edit-mode.
Open 'Search More...'-Dialog from an Man2one field.
Now you see the missing column in the table header.

**Current behavior**
All data columns are shifted to right to there table heads.

**Expected behavior**
Table heads and data in same column.
![error_web_list_view_sequence](https://cloud.githubusercontent.com/assets/8363288/16405365/6946496c-3d07-11e6-849a-48e7157589fe.jpg)

**Comment by elicoidal** [comment]
Hi @mharenz thanks for your report.
Can you tell us which browser and OS you are currently using?

**Comment by mharenz** [comment]
Hello,
I have tested it with:
- Debian 8 and Iceweasel 42.0
- Windows 7 Professional and Google chrome Version 51.0.2704.103 
- Windows 7 Professional and Firefox 47.0

The error appears in all variants.

**Comment by elicoidal** [comment]
Thanks for the feedback: we will have a look at it and come back to you (@siyuancn @duanyp1991)

**Comment by mharenz** [comment]
Hello, this issues still exists. Do you forgot it?

**Comment by elicoidal** [comment]
Sorry for the delay!

@victormartinelicocorp can you get someone working on this issue?

**Comment by victor-ditay** [comment]
@elicoidal Need to check availability but sure we'll take care
