### ISSUE TITLE
Odoo Client Error  SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data

### ISSUE THREAD

**Issue by zahidali746** [Elico-Corp/odoo-8.0#197]
When i install the this module it was working fine at that time but after one months it was not opening and was showing the following errorr.

Odoo Client Error  SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data

Please help i really need it.

**Comment by elicoidal** [comment]
@zahidali746 
Which module are you talking about?
Can you install the module in a fresh database?

**Comment by elicoidal** [comment]
No feedback: closing
