### ISSUE TITLE
[8.0][BUG] Missing dependency

### ISSUE THREAD

**Issue by jlaloux** [Elico-Corp/odoo-8.0#97]
Module is using relation to tables "mrp_production" and "purchase_order" so you need to have these modules in dependencies because if these modules are not installed, you have an error when you want to print the report

![image](https://cloud.githubusercontent.com/assets/7678583/15782233/c7f331f8-29a9-11e6-8ef2-e244999cc11d.png)

**Comment by elicoidal** [comment]
Hi @jlaloux Thanks for reporting!
We will fix this asap (@Rona111)

**Comment by Rona111** [comment]
@jlaloux I have add the dependencies of the module,Tks for your reporting.
@elicoidal please have a check.

**Comment by elicoidal** [comment]
Fix by #98
